[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "decision_module_manager"
version = "2024.26.05"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
events = {git = "https://github.com/BobryTeam/events.git"}